name: Compat Helper

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  compat-helper:
    name: Run Compat Helper
    runs-on: ubuntu-latest
    steps:
      - name: Add CompatHelper Package
        run: julia -e 'using Pkg; Pkg.add("CompatHelper")'

      - name: Run CompatHelper to Update Dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # COMPATHELPER_PRIV: ${{ secrets.DOCUMENTER_KEY }}
        run: julia -e 'using CompatHelper; CompatHelper.main(;subdirs=["", "docs"])'
